#!/usr/bin/env python3

import boto3

attrs = {
  'endpoint_url': 'http://localhost:8000'
}

# unset endpoint url for use with production database
if len(sys.argv) == 2:
  if "prod" in sys.argv[1]:
    attrs = {}
ddb = boto3.resource('ddb',**attrs)
table_name = 'cruddur_messages'

table = ddb.Table(table_name)
respponse = table.scan()

print('=====')
print(response)

items = response['items]
for item in items:
    print(item)
